# build env
FROM node:19.8.1-alpine as build
WORKDIR /app

COPY ./spa/package*.json ./
RUN npm ci
COPY ./spa/ ./
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./spa/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]