FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY /thumbservice .

RUN go build -o thumbservice

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/thumbservice .
COPY --from=builder /app/assets /app/assets

EXPOSE 8080

# CMD sh -c "sleep infinity"
CMD ["./thumbservice"]