services:
  kubes3-backend-srv:
    image: ghcr.io/xamma/kubes3-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
        - "8000:8000"
  kubes3-frontend-srv:
    image: ghcr.io/xamma/kubes3-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
        - "80:80"
  minio:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
    volumes:
      - my_s3_data:/data
volumes:
  my_s3_data: