apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tlssecret }}
  issuerRef:
    name: {{ .Values.ingress.issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}