---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.nginxRewriteTarget }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.ingress.httpService }}
            port:
              number: {{ .Values.ingress.portNumber }}