---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.service.frontend.appSelector }}
  type: {{ .Values.service.frontend.type }}
  ports:
  - name: frontend
    protocol: TCP
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}