---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.minio.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.service.minio.appSelector }}
  type: {{ .Values.service.minio.type }}
  ports:
  - name: s3
    protocol: TCP
    port: {{ .Values.service.minio.port }}
    targetPort: {{ .Values.service.minio.targetPort }}